prepare:
  split: 0.20
  seed: 20170428

featurize:
  max_features: 100
  ngrams: 1

train:
  seed: 20170428
  n_est: 50
  min_split: 0.01

experiment:
  name: shining_moonlight

experiment_2:
  names:
  - screaming_cat
  - sobbing_dog
